#!/bin/bash
#####################################################################################
# Copyright (c) 2019, NVIDIA CORPORATION. All rights reserved.

# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#####################################################################################

# FIXME: Modify the library lookup path to compensate for a problem with ZED shared libraries for
#        Jetson Xavier
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:_solib_arm64-v8a/_U@zed_Uaarch64_Uxavier_S_S_Czed_Uaarch64_Uxavier___Uexternal_Szed_Uaarch64_Uxavier_Saarch64_Slib/

# Check number of arguments
if [ "$#" == 0 ]; then
    echo "Please supply path to the program you would like to run, e.g., ./run apps/samples/simple_robot/simple_robot"
    exit 1
fi

filename=$1

# Check if the file exists
if [ ! -f $filename ]; then
    echo "Could not find a file named '$filename'."
    exit 1
fi

# Get file type. We'll handle binaries and Python scripts differently
file_type=$(file -b --mime-type $filename)

if [[ $file_type == "application/x-executable" ]]; then
    echo "Running your binary"
    # Run the program with arguments
    "$@"
elif [[ $file_type == "text/x-python" ]]; then
    if [[ $filename != *.py ]]; then
      echo "Please provide the original Python script with 'py' extension."
      exit 1
    fi
    echo "Running your Python script"
    # Update PYTHONPATH and run the program with arguments
    PYTHONPATH=$PWD:$PWD/packages/pyalice:$PWD/packages/ml python3 "$@"
elif [[ $file_type == "text/x-shellscript" ]]; then
    echo "Running your Python script"
    "$@"
else
    echo "'$filename' has unsupported file type: '$file_type'"
    exit 1
fi
