# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

api_version: 1.0

joint_limit_buffers: [.01, .01, .01, .01, .01, .01]

rmp_params:
    cspace_target_rmp:
        metric_scalar: 50.
        position_gain: 100.
        damping_gain: 50.
        robust_position_term_thresh: .5
        inertia: 1.
    cspace_trajectory_rmp:
        p_gain: 80.
        d_gain: 10.
        ff_gain: .25
        weight: 50.
    cspace_affine_rmp:
        final_handover_time_std_dev: .25
        weight: 2000.
    joint_limit_rmp:
        metric_scalar: 1000.
        metric_length_scale: .01
        metric_exploder_eps: 1e-3
        metric_velocity_gate_length_scale: .01
        accel_damper_gain: 200.
        accel_potential_gain: 1.
        accel_potential_exploder_length_scale: .1
        accel_potential_exploder_eps: 1e-2
    joint_velocity_cap_rmp:
        max_velocity: 2.15
        velocity_damping_region: 0.5
        damping_gain: 300.
        metric_weight: 100.
    target_rmp:
        accel_p_gain: 80.
        accel_d_gain: 120.
        accel_norm_eps: .075
        metric_alpha_length_scale: .05
        min_metric_alpha: .01
        max_metric_scalar: 10000.
        min_metric_scalar: 2500.
        proximity_metric_boost_scalar: 20.
        proximity_metric_boost_length_scale: .02
        accept_user_weights: false
    axis_target_rmp:
        accel_p_gain: 200.
        accel_d_gain: 40.
        metric_scalar: 10.
        proximity_metric_boost_scalar: 3000.
        proximity_metric_boost_length_scale: .05
        accept_user_weights: false
    collision_rmp:
        damping_gain: 50.
        damping_std_dev: .04
        damping_robustness_eps: 1e-2
        damping_velocity_gate_length_scale: .01
        repulsion_gain: 1200.
        repulsion_std_dev: .01
        metric_modulation_radius: .5
        metric_scalar: 0.        # turn off collision avoidance
        # metric_scalar: 10000.  # typical value with collisions enabled
        metric_exploder_std_dev: .02
        metric_exploder_eps: .001
    damping_rmp:
        accel_d_gain: 30.
        metric_scalar: 50.
        inertia: 100.

canonical_resolve:
    max_acceleration_norm: 50.
    projection_tolerance: .01
    verbose: false

body_cylinders:
    - name: base_stem
      pt1: [0,0,.333]
      pt2: [0,0,0.]
      radius: .05
    - name: base_tee
      pt1: [0,0,.333]
      pt2: [0,0,.333]
      radius: .15

body_collision_controllers:
    - name: base
      radius: .08
    - name: shoulder
      radius: .08
    - name: elbow
      radius: .05
    - name: wrist_1
      radius: .03
    - name: wrist_2
      radius: .03
    - name: wrist_3
      radius: .02
    - name: tool
      radius: .05

arm_collision_controllers:
  - segment: [shoulder, wrist_1]
    interpolation_pts: 10
    radius: .1
  - segment: [elbow, wrist_2]
    interpolation_pts: 5
    radius: .08
    suppression_group_name: tool
  - segment: [wrist_1, wrist_2]
    interpolation_pts: 5
    radius: .08
    suppression_group_name: tool
  - segment: [wrist_2, wrist_3]
    interpolation_pts: 5
    radius: .05
    suppression_group_name: tool
  - segment: [wrist_3, tool]
    interpolation_pts: 5
    radius: .05
    suppression_group_name: tool
